// ============================================================
// Export: SPICE Netlist Generator
// ============================================================

import type { SchematicDocument, Netlist, Net, SchematicComponent } from '@/types';
import { buildNetlist } from '@/lib/engine/netlist';
import { getComponentById } from '@/lib/component-library';

export function generateSpiceNetlist(schematic: SchematicDocument, title?: string): string {
  const netlist = buildNetlist(schematic);
  const lines: string[] = [];

  lines.push(`* ${title || 'LochCAD SPICE Netlist'}`);
  lines.push(`* Generated by LochCAD`);
  lines.push(`* Date: ${new Date().toISOString()}`);
  lines.push('');

  // Build net name map  (net name -> net number for SPICE)
  const netMap = new Map<string, number>();
  let netNum = 1;
  for (const net of netlist.nets) {
    if (net.name.toLowerCase() === 'gnd' || net.name === '0') {
      netMap.set(net.name, 0);
    } else {
      netMap.set(net.name, netNum++);
    }
  }

  // Components
  for (const comp of schematic.components) {
    const def = getComponentById(comp.libraryId);
    if (!def) continue;

    const spiceTemplate = def.spiceTemplate ?? def.spice?.template;
    if (!spiceTemplate) {
      lines.push(`* ${comp.reference} - No SPICE model`);
      continue;
    }

    let tpl = spiceTemplate;

    // Replace {ref}
    tpl = tpl.replace('{ref}', comp.reference);

    // Replace {value}
    tpl = tpl.replace('{value}', comp.value || '?');

    // Replace pin numbers {1}, {2}, etc.
    for (const pin of def.symbol.pins) {
      // Find the net this pin belongs to
      const net = netlist.nets.find(n =>
        n.connections.some(p => p.componentRef === comp.reference && p.pinNumber === pin.number)
      );
      const netId = net ? (netMap.get(net.name) ?? 0) : 0;
      tpl = tpl.replace(`{${pin.number}}`, netId.toString());
    }

    lines.push(tpl);
  }

  // SPICE models from component definitions
  lines.push('');
  lines.push('* --- Models ---');
  const modelsSeen = new Set<string>();
  for (const comp of schematic.components) {
    const def = getComponentById(comp.libraryId);
    if (!def?.spiceModel) continue;
    if (modelsSeen.has(def.spiceModel)) continue;
    modelsSeen.add(def.spiceModel);
    lines.push(def.spiceModel);
  }

  lines.push('');
  lines.push('.end');

  return lines.join('\n');
}

// ============================================================
// Export: BOM (Bill of Materials)
// ============================================================

export interface BOMEntry {
  reference: string;
  value: string;
  description: string;
  footprint: string;
  quantity: number;
  category?: string;
  manufacturer?: string;
  partNumber?: string;
  unit?: string;
  remarks?: string;
}

export function generateBOM(schematic: SchematicDocument): BOMEntry[] {
  const grouped = new Map<string, BOMEntry>();

  for (const comp of schematic.components) {
    const def = getComponentById(comp.libraryId);
    const key = `${comp.value}|${def?.name || ''}`;

    if (grouped.has(key)) {
      const entry = grouped.get(key)!;
      entry.quantity++;
      entry.reference += `, ${comp.reference}`;
    } else {
      grouped.set(key, {
        reference: comp.reference,
        value: comp.value || '',
        description: def?.description || def?.name || '',
        footprint: def?.footprint?.pads?.length
          ? `${def.footprint.pads.length}-pin`
          : '',
        quantity: 1,
        category: def?.category || '',
        manufacturer: comp.properties?.manufacturer || def?.defaultProperties?.manufacturer || '',
        partNumber: comp.properties?.partNumber || def?.defaultProperties?.partNumber || '',
        unit: 'Stk.',
        remarks: comp.properties?.remarks || '',
      });
    }
  }

  return Array.from(grouped.values()).sort((a, b) => a.reference.localeCompare(b.reference));
}

export function bomToCsv(bom: BOMEntry[]): string {
  const header = 'Referenz;Wert;Beschreibung;Footprint;Anzahl';
  const rows = bom.map(e =>
    `${e.reference};${e.value};${e.description};${e.footprint};${e.quantity}`
  );
  return [header, ...rows].join('\n');
}

export interface BOMProjectInfo {
  name: string;
  description?: string;
  author?: string;
  version?: string;
  createdAt?: string;
  sheetCount?: number;
  documentNumber?: string;
  revision?: string;
  approvedBy?: string;
  department?: string;
  classification?: string;
}

/**
 * Generates a DIN EN 62027 compliant HTML Bill of Materials
 * with a title block per DIN EN ISO 7200.
 */
export function bomToHtml(bom: BOMEntry[], info?: BOMProjectInfo): string {
  const now = new Date();
  const dateStr = now.toLocaleDateString('de-DE', { day: '2-digit', month: '2-digit', year: 'numeric' });
  const totalParts = bom.reduce((s, e) => s + e.quantity, 0);
  const totalPositions = bom.length;
  const projName = info?.name || 'Unbenanntes Projekt';
  const projDesc = info?.description || '\u2014';
  const projAuthor = info?.author || '\u2014';
  const projVersion = info?.version || '1.0';
  const projCreated = info?.createdAt
    ? new Date(info.createdAt).toLocaleDateString('de-DE', { day: '2-digit', month: '2-digit', year: 'numeric' })
    : '\u2014';
  const sheetCount = info?.sheetCount ?? 1;
  const docNumber = info?.documentNumber || `BOM-${projName.replace(/\s+/g, '-').substring(0, 20).toUpperCase()}`;
  const revision = info?.revision || projVersion;
  const approvedBy = info?.approvedBy || '';
  const department = info?.department || '';
  const classification = info?.classification || 'Intern';

  // Group entries by category for DIN EN 62027 structured listing
  const categories = new Map<string, BOMEntry[]>();
  for (const entry of bom) {
    const cat = entry.category || 'Sonstige';
    if (!categories.has(cat)) categories.set(cat, []);
    categories.get(cat)!.push(entry);
  }
  const sortedCategories = Array.from(categories.entries()).sort((a, b) => a[0].localeCompare(b[0]));

  // Build table rows grouped by category
  let pos = 0;
  let rows = '';
  for (const [catName, entries] of sortedCategories) {
    rows += `
        <tr class="category-row">
          <td colspan="9">${esc(catName)}</td>
        </tr>`;
    for (const e of entries) {
      pos++;
      rows += `
        <tr>
          <td class="center">${pos}</td>
          <td class="center">${e.quantity}</td>
          <td class="center">${esc(e.unit || 'Stk.')}</td>
          <td class="mono">${esc(e.reference)}</td>
          <td>${esc(e.description)}</td>
          <td class="mono">${esc(e.value)}</td>
          <td>${esc(e.footprint)}</td>
          <td>${esc(e.manufacturer || '')}</td>
          <td>${esc(e.partNumber || '')}</td>
        </tr>`;
    }
  }

  return `<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="utf-8">
  <title>St\u00fcckliste \u2014 ${esc(projName)}</title>
  <style>
    /* ==== Reset & Base ==== */
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    html { font-size: 9pt; }
    body {
      font-family: 'Helvetica Neue', Helvetica, Arial, 'Liberation Sans', sans-serif;
      color: #111;
      background: #d0d0d0;
      padding: 16px;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }

    /* ==== A4 Page Container ==== */
    .page {
      width: 210mm;
      min-height: 297mm;
      margin: 0 auto;
      background: #fff;
      padding: 10mm 12mm 18mm 12mm;
      box-shadow: 0 2px 12px rgba(0,0,0,.25);
      position: relative;
    }

    /* ============================================================
       DIN EN ISO 7200 Title Block (Schriftfeld)
       ============================================================ */
    .title-block {
      width: 100%;
      border-collapse: collapse;
      border: 1.2pt solid #000;
      margin-bottom: 5mm;
      font-size: 8pt;
      page-break-inside: avoid;
    }
    .title-block td, .title-block th {
      border: 0.6pt solid #000;
      padding: 1.5mm 2.5mm;
      vertical-align: middle;
      line-height: 1.35;
    }
    .title-block th {
      background: #f3f3f3;
      font-weight: 600;
      text-align: left;
      width: 16%;
      font-size: 7.5pt;
      color: #333;
      text-transform: uppercase;
      letter-spacing: 0.04em;
    }
    .title-block .tb-logo {
      text-align: center;
      font-weight: 800;
      font-size: 13pt;
      color: #1a6aab;
      letter-spacing: 0.08em;
      vertical-align: middle;
      border-left: 1.2pt solid #000;
    }
    .title-block .tb-project {
      font-size: 15pt;
      font-weight: 700;
      letter-spacing: 0.01em;
    }
    .title-block .tb-doctype {
      font-size: 10pt;
      font-weight: 600;
    }
    .title-block .tb-norm {
      font-size: 7pt;
      color: #555;
      font-weight: 400;
    }
    .title-block .tb-small {
      font-size: 7pt;
      color: #444;
    }

    /* ============================================================
       DIN EN 62027 BOM Table (Stückliste)
       ============================================================ */
    .bom-section-title {
      font-size: 10pt;
      font-weight: 700;
      margin: 3mm 0 1.5mm 0;
      padding-bottom: 1mm;
      border-bottom: 0.8pt solid #000;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }

    .bom-table {
      width: 100%;
      border-collapse: collapse;
      border: 1.2pt solid #000;
      font-size: 8pt;
      page-break-inside: auto;
    }
    .bom-table thead { display: table-header-group; }
    .bom-table thead th {
      background: #1a6aab;
      color: #fff;
      font-weight: 600;
      padding: 2mm 2mm;
      text-align: left;
      border: 0.6pt solid #000;
      white-space: nowrap;
      font-size: 7.5pt;
      text-transform: uppercase;
      letter-spacing: 0.03em;
    }
    .bom-table tbody td {
      padding: 1.4mm 2mm;
      border: 0.4pt solid #bbb;
      border-left: 0.4pt solid #999;
      border-right: 0.4pt solid #999;
      vertical-align: top;
      line-height: 1.3;
    }
    .bom-table tbody tr:nth-child(even):not(.category-row) { background: #f6f8fb; }
    .bom-table tbody tr:hover:not(.category-row) { background: #e3edf7; }
    .bom-table .center { text-align: center; }
    .bom-table .mono { font-family: 'Consolas', 'Liberation Mono', 'Courier New', monospace; font-size: 7.5pt; }

    /* Column widths conforming to DIN EN 62027 field priority */
    .bom-table .col-pos  { width: 6%; text-align: center; }
    .bom-table .col-qty  { width: 6%; text-align: center; }
    .bom-table .col-unit { width: 5%; text-align: center; }
    .bom-table .col-ref  { width: 12%; }
    .bom-table .col-desc { width: 22%; }
    .bom-table .col-val  { width: 12%; }
    .bom-table .col-fp   { width: 11%; }
    .bom-table .col-mfr  { width: 13%; }
    .bom-table .col-pn   { width: 13%; }

    /* Category group header */
    .category-row td {
      background: #e8ecf0 !important;
      font-weight: 700;
      font-size: 7.5pt;
      text-transform: uppercase;
      letter-spacing: 0.04em;
      padding: 1.8mm 2.5mm !important;
      border-top: 0.8pt solid #000;
      border-bottom: 0.4pt solid #888;
      color: #1a6aab;
    }

    /* Summary / Totals */
    .bom-table tfoot td {
      padding: 2mm 2.5mm;
      border: 1.2pt solid #000;
      font-weight: 700;
      background: #f3f3f3;
      font-size: 8.5pt;
    }

    /* ============================================================
       Approval / Revision Block (after table)
       ============================================================ */
    .approval-block {
      width: 100%;
      border-collapse: collapse;
      border: 1.2pt solid #000;
      margin-top: 5mm;
      font-size: 7.5pt;
      page-break-inside: avoid;
    }
    .approval-block td, .approval-block th {
      border: 0.6pt solid #000;
      padding: 1.5mm 2.5mm;
      vertical-align: middle;
    }
    .approval-block th {
      background: #f3f3f3;
      font-weight: 600;
      text-align: left;
      text-transform: uppercase;
      font-size: 7pt;
      color: #333;
      letter-spacing: 0.04em;
      width: 16%;
    }
    .approval-block .sign-cell {
      height: 10mm;
      min-width: 30mm;
    }

    /* ============================================================
       Norm Reference Footer
       ============================================================ */
    .norm-footer {
      margin-top: 4mm;
      font-size: 6.5pt;
      color: #888;
      border-top: 0.4pt solid #ccc;
      padding-top: 1.5mm;
      display: flex;
      justify-content: space-between;
    }
    .norm-footer span { display: inline-block; }

    /* ============================================================
       Page Footer (fixed on print)
       ============================================================ */
    .page-footer {
      position: absolute;
      bottom: 8mm;
      left: 12mm;
      right: 12mm;
      display: flex;
      justify-content: space-between;
      font-size: 6.5pt;
      color: #777;
      border-top: 0.4pt solid #bbb;
      padding-top: 1.5mm;
    }

    /* ============================================================
       Print Styles
       ============================================================ */
    @media print {
      html { font-size: 9pt; }
      body { background: none; padding: 0; margin: 0; }
      .page {
        box-shadow: none;
        border: none;
        padding: 8mm 12mm 14mm 12mm;
        margin: 0;
        width: 100%;
        min-height: auto;
      }
      .bom-table tbody tr:hover { background: inherit; }
      .bom-table tbody tr:nth-child(even):not(.category-row) { background: #f6f8fb; }
      .bom-table thead { display: table-header-group; }
      .bom-table tr { page-break-inside: avoid; }
      .page-footer { position: fixed; bottom: 4mm; left: 12mm; right: 12mm; }
      .norm-footer { page-break-before: avoid; }

      @page {
        size: A4 landscape;
        margin: 8mm 10mm;
      }
    }
  </style>
</head>
<body>
  <div class="page">
    <!-- ============================================================
         DIN EN ISO 7200 — Schriftfeld (Title Block)
         ============================================================ -->
    <table class="title-block">
      <colgroup>
        <col style="width:16%">
        <col style="width:22%">
        <col style="width:10%">
        <col style="width:20%">
        <col style="width:16%">
        <col style="width:16%">
      </colgroup>
      <tr>
        <th>Projekt</th>
        <td colspan="3" class="tb-project">${esc(projName)}</td>
        <td rowspan="4" colspan="2" class="tb-logo">
          <div style="margin-bottom:2mm;">LochCAD</div>
          <div style="font-size:7pt;font-weight:400;color:#555;letter-spacing:0;">EDA \u00b7 Schaltplanentwurf</div>
        </td>
      </tr>
      <tr>
        <th>Dokumenttyp</th>
        <td class="tb-doctype" colspan="2">St\u00fcckliste (BOM)</td>
        <td class="tb-norm">nach DIN EN 62027 / IEC 62027</td>
      </tr>
      <tr>
        <th>Beschreibung</th>
        <td colspan="3">${esc(projDesc)}</td>
      </tr>
      <tr>
        <th>Klassifikation</th>
        <td colspan="3">${esc(classification)}</td>
      </tr>
      <tr>
        <th>Dokument-Nr.</th>
        <td class="mono" style="font-family:monospace;letter-spacing:0.05em;">${esc(docNumber)}</td>
        <th style="width:10%">Revision</th>
        <td><strong>${esc(revision)}</strong></td>
        <th>Bl\u00e4tter</th>
        <td class="center">${sheetCount}</td>
      </tr>
      <tr>
        <th>Erstellt von</th>
        <td>${esc(projAuthor)}</td>
        <th>Erstellt am</th>
        <td>${esc(projCreated)}</td>
        <th>Druckdatum</th>
        <td>${dateStr}</td>
      </tr>
      <tr>
        <th>Abteilung</th>
        <td>${esc(department)}</td>
        <th>Positionen</th>
        <td class="center"><strong>${totalPositions}</strong></td>
        <th>Bauteile</th>
        <td class="center"><strong>${totalParts}</strong></td>
      </tr>
    </table>

    <!-- ============================================================
         DIN EN 62027 — Stückliste (Parts List)
         ============================================================ -->
    <div class="bom-section-title">St\u00fcckliste / Teile\u00fcbersicht</div>
    <table class="bom-table">
      <thead>
        <tr>
          <th class="col-pos">Pos.</th>
          <th class="col-qty">Menge</th>
          <th class="col-unit">Einh.</th>
          <th class="col-ref">Referenz</th>
          <th class="col-desc">Benennung</th>
          <th class="col-val">Wert</th>
          <th class="col-fp">Bauform</th>
          <th class="col-mfr">Hersteller</th>
          <th class="col-pn">Bestell-Nr.</th>
        </tr>
      </thead>
      <tbody>${rows}
      </tbody>
      <tfoot>
        <tr>
          <td colspan="1" class="center">${totalPositions}</td>
          <td colspan="1" class="center">${totalParts}</td>
          <td colspan="7" style="text-align:left;">Gesamtanzahl: ${totalPositions} Positionen, ${totalParts} Bauteile</td>
        </tr>
      </tfoot>
    </table>

    <!-- ============================================================
         Approval / Signature Block
         ============================================================ -->
    <table class="approval-block">
      <tr>
        <th>Bearbeitet</th>
        <td>${esc(projAuthor)}</td>
        <th>Datum</th>
        <td>${esc(projCreated)}</td>
        <th>Unterschrift</th>
        <td class="sign-cell"></td>
      </tr>
      <tr>
        <th>Gepr\u00fcft</th>
        <td>${esc(approvedBy)}</td>
        <th>Datum</th>
        <td></td>
        <th>Unterschrift</th>
        <td class="sign-cell"></td>
      </tr>
      <tr>
        <th>Freigegeben</th>
        <td></td>
        <th>Datum</th>
        <td></td>
        <th>Unterschrift</th>
        <td class="sign-cell"></td>
      </tr>
    </table>

    <!-- Norm reference -->
    <div class="norm-footer">
      <span>Erstellt gem\u00e4\u00df DIN EN 62027:2012 (IEC 62027:2011) \u2014 Listenerstellung</span>
      <span>Schriftfeld nach DIN EN ISO 7200</span>
      <span>${esc(docNumber)} Rev.\u00a0${esc(revision)}</span>
    </div>

    <!-- Page Footer -->
    <div class="page-footer">
      <span>St\u00fcckliste \u2014 ${esc(projName)} \u2014 ${dateStr}</span>
      <span>${esc(docNumber)}</span>
      <span>Erstellt mit LochCAD</span>
    </div>
  </div>
</body>
</html>`;
}

/** Escape HTML special characters */
function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
