// ============================================================
// Export: SPICE Netlist Generator
// ============================================================

import type { SchematicDocument, Netlist, Net, SchematicComponent } from '@/types';
import { buildNetlist } from '@/lib/engine/netlist';
import { getComponentById } from '@/lib/component-library';

export function generateSpiceNetlist(schematic: SchematicDocument, title?: string): string {
  const netlist = buildNetlist(schematic);
  const lines: string[] = [];

  lines.push(`* ${title || 'LochCAD SPICE Netlist'}`);
  lines.push(`* Generated by LochCAD`);
  lines.push(`* Date: ${new Date().toISOString()}`);
  lines.push('');

  // Build net name map  (net name -> net number for SPICE)
  const netMap = new Map<string, number>();
  let netNum = 1;
  for (const net of netlist.nets) {
    if (net.name.toLowerCase() === 'gnd' || net.name === '0') {
      netMap.set(net.name, 0);
    } else {
      netMap.set(net.name, netNum++);
    }
  }

  // Components
  for (const comp of schematic.components) {
    const def = getComponentById(comp.libraryId);
    if (!def) continue;

    const spiceTemplate = def.spiceTemplate ?? def.spice?.template;
    if (!spiceTemplate) {
      lines.push(`* ${comp.reference} - No SPICE model`);
      continue;
    }

    let tpl = spiceTemplate;

    // Replace {ref}
    tpl = tpl.replace('{ref}', comp.reference);

    // Replace {value}
    tpl = tpl.replace('{value}', comp.value || '?');

    // Replace pin numbers {1}, {2}, etc.
    for (const pin of def.symbol.pins) {
      // Find the net this pin belongs to
      const net = netlist.nets.find(n =>
        n.connections.some(p => p.componentRef === comp.reference && p.pinNumber === pin.number)
      );
      const netId = net ? (netMap.get(net.name) ?? 0) : 0;
      tpl = tpl.replace(`{${pin.number}}`, netId.toString());
    }

    lines.push(tpl);
  }

  // SPICE models from component definitions
  lines.push('');
  lines.push('* --- Models ---');
  const modelsSeen = new Set<string>();
  for (const comp of schematic.components) {
    const def = getComponentById(comp.libraryId);
    if (!def?.spiceModel) continue;
    if (modelsSeen.has(def.spiceModel)) continue;
    modelsSeen.add(def.spiceModel);
    lines.push(def.spiceModel);
  }

  lines.push('');
  lines.push('.end');

  return lines.join('\n');
}

// ============================================================
// Export: BOM (Bill of Materials)
// ============================================================

export interface BOMEntry {
  reference: string;
  value: string;
  description: string;
  footprint: string;
  quantity: number;
}

export function generateBOM(schematic: SchematicDocument): BOMEntry[] {
  const grouped = new Map<string, BOMEntry>();

  for (const comp of schematic.components) {
    const def = getComponentById(comp.libraryId);
    const key = `${comp.value}|${def?.name || ''}`;

    if (grouped.has(key)) {
      const entry = grouped.get(key)!;
      entry.quantity++;
      entry.reference += `, ${comp.reference}`;
    } else {
      grouped.set(key, {
        reference: comp.reference,
        value: comp.value || '',
        description: def?.description || def?.name || '',
        footprint: def?.footprint?.pads?.length
          ? `${def.footprint.pads.length}-pin`
          : '',
        quantity: 1,
      });
    }
  }

  return Array.from(grouped.values()).sort((a, b) => a.reference.localeCompare(b.reference));
}

export function bomToCsv(bom: BOMEntry[]): string {
  const header = 'Referenz;Wert;Beschreibung;Footprint;Anzahl';
  const rows = bom.map(e =>
    `${e.reference};${e.value};${e.description};${e.footprint};${e.quantity}`
  );
  return [header, ...rows].join('\n');
}

export function bomToHtml(bom: BOMEntry[]): string {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>LochCAD Stückliste</title>
  <style>
    body { font-family: 'Segoe UI', sans-serif; padding: 20px; background: #f5f5f5; }
    h1 { color: #1b1f2b; }
    table { border-collapse: collapse; width: 100%; background: white; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
    th { background: #2176B7; color: white; padding: 10px; text-align: left; }
    td { padding: 8px 10px; border-bottom: 1px solid #eee; }
    tr:hover { background: #f0f8ff; }
    .total { font-weight: bold; background: #e8f5e9; }
  </style>
</head>
<body>
  <h1>🔌 LochCAD — Stückliste (BOM)</h1>
  <p>Erstellt am: ${new Date().toLocaleDateString('de-DE')}</p>
  <table>
    <tr>
      <th>Referenz</th>
      <th>Wert</th>
      <th>Beschreibung</th>
      <th>Footprint</th>
      <th>Anzahl</th>
    </tr>
    ${bom.map(e => `
    <tr>
      <td>${e.reference}</td>
      <td>${e.value}</td>
      <td>${e.description}</td>
      <td>${e.footprint}</td>
      <td>${e.quantity}</td>
    </tr>`).join('')}
    <tr class="total">
      <td colspan="4">Gesamt</td>
      <td>${bom.reduce((s, e) => s + e.quantity, 0)}</td>
    </tr>
  </table>
</body>
</html>`;
}
